"""Service contracts and MVP stubs for replaceable analysis engines."""

from app.services.interfaces import (
    AnalysisArtifact,
    AnalysisInput,
    AgentEvaluationService,
    AudioAnalysisService,
    DocumentParseResult,
    DocumentParserService,
    GazeAnalysisService,
    PoseAnalysisService,
    QaGenerationService,
    ReportGenerationService,
    ScriptGenerationService,
    SlideAnalysisService,
)
from app.services.presentations import (
    MAX_TOTAL_DURATION_SECONDS,
    MIN_PRESENTATION_DURATION_SECONDS,
    MIN_TOTAL_DURATION_SECONDS,
    PRESENTATION_INVALID_TIME_RANGE_MESSAGE,
    PRESENTATION_NOT_FOUND_MESSAGE,
    PresentationTimeValidationResult,
    calculate_presentation_duration_seconds,
    create_presentation_project,
    get_presentation_project,
    list_presentation_projects,
    validate_presentation_time_input,
)
from app.services.refresh_tokens import (
    RefreshTokenError,
    RefreshTokenIssue,
    RefreshTokenRotation,
    RefreshTokenService,
    TokenPair,
)
from app.services.stub_policy import (
    DEFAULT_STUB_POLICY,
    MVP_STUB_SERVICE_DESCRIPTORS,
    StubPolicy,
    StubServiceDescriptor,
    get_stub_service_descriptors,
)
from app.services.stubs import DeterministicMvpAnalysisStub
from app.services.users import (
    INVALID_CREDENTIALS_MESSAGE,
    REFRESH_TOKEN_INVALID_MESSAGE,
    USER_ALREADY_EXISTS_MESSAGE,
    LoginResult,
    TokenRefreshResult,
    create_user_account,
    get_user_by_email,
    login_user_account,
    logout_user_account,
    refresh_user_token_pair,
    update_user_profile,
)

__all__ = [
    "AnalysisArtifact",
    "AnalysisInput",
    "AgentEvaluationService",
    "AudioAnalysisService",
    "DEFAULT_STUB_POLICY",
    "DeterministicMvpAnalysisStub",
    "DocumentParseResult",
    "DocumentParserService",
    "GazeAnalysisService",
    "INVALID_CREDENTIALS_MESSAGE",
    "LoginResult",
    "MVP_STUB_SERVICE_DESCRIPTORS",
    "MAX_TOTAL_DURATION_SECONDS",
    "MIN_PRESENTATION_DURATION_SECONDS",
    "MIN_TOTAL_DURATION_SECONDS",
    "PoseAnalysisService",
    "PRESENTATION_INVALID_TIME_RANGE_MESSAGE",
    "PRESENTATION_NOT_FOUND_MESSAGE",
    "PresentationTimeValidationResult",
    "QaGenerationService",
    "REFRESH_TOKEN_INVALID_MESSAGE",
    "ReportGenerationService",
    "RefreshTokenError",
    "RefreshTokenIssue",
    "RefreshTokenRotation",
    "RefreshTokenService",
    "ScriptGenerationService",
    "SlideAnalysisService",
    "StubPolicy",
    "StubServiceDescriptor",
    "TokenPair",
    "TokenRefreshResult",
    "USER_ALREADY_EXISTS_MESSAGE",
    "calculate_presentation_duration_seconds",
    "create_presentation_project",
    "create_user_account",
    "get_presentation_project",
    "get_stub_service_descriptors",
    "get_user_by_email",
    "login_user_account",
    "logout_user_account",
    "list_presentation_projects",
    "refresh_user_token_pair",
    "update_user_profile",
    "validate_presentation_time_input",
]
