"""Canonical domain error codes exposed by API failure responses."""

from enum import StrEnum


class ErrorDomain(StrEnum):
    COMMON = "COMMON"
    AUTH = "AUTH"
    USER = "USER"
    PRESENTATION = "PRESENTATION"
    PRESENTATION_FILE = "PRESENTATION_FILE"
    SLIDE = "SLIDE"
    ANALYSIS = "ANALYSIS"
    TIMING = "TIMING"
    SCRIPT = "SCRIPT"
    REHEARSAL = "REHEARSAL"
    MEDIA = "MEDIA"
    AUDIO_ANALYSIS = "AUDIO_ANALYSIS"
    POSE_ANALYSIS = "POSE_ANALYSIS"
    GAZE_ANALYSIS = "GAZE_ANALYSIS"
    EVALUATION = "EVALUATION"
    QA = "QA"
    REPORT = "REPORT"
    JOB = "JOB"
    SYSTEM = "SYSTEM"


class ErrorCode(StrEnum):
    HTTP_ERROR = "HTTP_ERROR"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    VALIDATION_ERROR = "VALIDATION_ERROR"
    AUTHENTICATION_REQUIRED = "AUTHENTICATION_REQUIRED"
    INVALID_CREDENTIALS = "INVALID_CREDENTIALS"
    TOKEN_EXPIRED = "TOKEN_EXPIRED"
    TOKEN_INVALID = "TOKEN_INVALID"
    PERMISSION_DENIED = "PERMISSION_DENIED"
    USER_NOT_FOUND = "USER_NOT_FOUND"
    USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS"
    PRESENTATION_NOT_FOUND = "PRESENTATION_NOT_FOUND"
    PRESENTATION_INVALID_TIME_RANGE = "PRESENTATION_INVALID_TIME_RANGE"
    PRESENTATION_INVALID_STATUS_TRANSITION = "PRESENTATION_INVALID_STATUS_TRANSITION"
    PRESENTATION_FILE_NOT_FOUND = "PRESENTATION_FILE_NOT_FOUND"
    PRESENTATION_FILE_UNSUPPORTED_TYPE = "PRESENTATION_FILE_UNSUPPORTED_TYPE"
    PRESENTATION_FILE_TOO_LARGE = "PRESENTATION_FILE_TOO_LARGE"
    SLIDE_NOT_FOUND = "SLIDE_NOT_FOUND"
    SLIDE_INVALID_ORDER = "SLIDE_INVALID_ORDER"
    ANALYSIS_NOT_FOUND = "ANALYSIS_NOT_FOUND"
    ANALYSIS_NOT_READY = "ANALYSIS_NOT_READY"
    TIMING_NOT_FOUND = "TIMING_NOT_FOUND"
    TIMING_TOTAL_MISMATCH = "TIMING_TOTAL_MISMATCH"
    SCRIPT_NOT_FOUND = "SCRIPT_NOT_FOUND"
    SCRIPT_NOT_READY = "SCRIPT_NOT_READY"
    REHEARSAL_NOT_FOUND = "REHEARSAL_NOT_FOUND"
    REHEARSAL_INVALID_STATUS_TRANSITION = "REHEARSAL_INVALID_STATUS_TRANSITION"
    MEDIA_NOT_FOUND = "MEDIA_NOT_FOUND"
    MEDIA_UNSUPPORTED_TYPE = "MEDIA_UNSUPPORTED_TYPE"
    AUDIO_ANALYSIS_NOT_FOUND = "AUDIO_ANALYSIS_NOT_FOUND"
    AUDIO_ANALYSIS_NOT_READY = "AUDIO_ANALYSIS_NOT_READY"
    POSE_ANALYSIS_NOT_FOUND = "POSE_ANALYSIS_NOT_FOUND"
    POSE_ANALYSIS_NOT_READY = "POSE_ANALYSIS_NOT_READY"
    GAZE_ANALYSIS_NOT_FOUND = "GAZE_ANALYSIS_NOT_FOUND"
    GAZE_ANALYSIS_NOT_READY = "GAZE_ANALYSIS_NOT_READY"
    EVALUATION_NOT_FOUND = "EVALUATION_NOT_FOUND"
    EVALUATION_NOT_READY = "EVALUATION_NOT_READY"
    QA_SESSION_NOT_FOUND = "QA_SESSION_NOT_FOUND"
    QA_QUESTION_NOT_FOUND = "QA_QUESTION_NOT_FOUND"
    QA_ANSWER_NOT_FOUND = "QA_ANSWER_NOT_FOUND"
    REPORT_NOT_FOUND = "REPORT_NOT_FOUND"
    REPORT_NOT_READY = "REPORT_NOT_READY"
    JOB_NOT_FOUND = "JOB_NOT_FOUND"
    JOB_CANNOT_BE_CANCELLED = "JOB_CANNOT_BE_CANCELLED"
    DEPENDENCY_UNAVAILABLE = "DEPENDENCY_UNAVAILABLE"


ERROR_CODES_BY_DOMAIN: dict[ErrorDomain, tuple[ErrorCode, ...]] = {
    ErrorDomain.COMMON: (
        ErrorCode.HTTP_ERROR,
        ErrorCode.VALIDATION_ERROR,
        ErrorCode.PERMISSION_DENIED,
    ),
    ErrorDomain.AUTH: (
        ErrorCode.AUTHENTICATION_REQUIRED,
        ErrorCode.INVALID_CREDENTIALS,
        ErrorCode.TOKEN_EXPIRED,
        ErrorCode.TOKEN_INVALID,
    ),
    ErrorDomain.USER: (
        ErrorCode.USER_NOT_FOUND,
        ErrorCode.USER_ALREADY_EXISTS,
    ),
    ErrorDomain.PRESENTATION: (
        ErrorCode.PRESENTATION_NOT_FOUND,
        ErrorCode.PRESENTATION_INVALID_TIME_RANGE,
        ErrorCode.PRESENTATION_INVALID_STATUS_TRANSITION,
    ),
    ErrorDomain.PRESENTATION_FILE: (
        ErrorCode.PRESENTATION_FILE_NOT_FOUND,
        ErrorCode.PRESENTATION_FILE_UNSUPPORTED_TYPE,
        ErrorCode.PRESENTATION_FILE_TOO_LARGE,
    ),
    ErrorDomain.SLIDE: (
        ErrorCode.SLIDE_NOT_FOUND,
        ErrorCode.SLIDE_INVALID_ORDER,
    ),
    ErrorDomain.ANALYSIS: (
        ErrorCode.ANALYSIS_NOT_FOUND,
        ErrorCode.ANALYSIS_NOT_READY,
    ),
    ErrorDomain.TIMING: (
        ErrorCode.TIMING_NOT_FOUND,
        ErrorCode.TIMING_TOTAL_MISMATCH,
    ),
    ErrorDomain.SCRIPT: (
        ErrorCode.SCRIPT_NOT_FOUND,
        ErrorCode.SCRIPT_NOT_READY,
    ),
    ErrorDomain.REHEARSAL: (
        ErrorCode.REHEARSAL_NOT_FOUND,
        ErrorCode.REHEARSAL_INVALID_STATUS_TRANSITION,
    ),
    ErrorDomain.MEDIA: (
        ErrorCode.MEDIA_NOT_FOUND,
        ErrorCode.MEDIA_UNSUPPORTED_TYPE,
    ),
    ErrorDomain.AUDIO_ANALYSIS: (
        ErrorCode.AUDIO_ANALYSIS_NOT_FOUND,
        ErrorCode.AUDIO_ANALYSIS_NOT_READY,
    ),
    ErrorDomain.POSE_ANALYSIS: (
        ErrorCode.POSE_ANALYSIS_NOT_FOUND,
        ErrorCode.POSE_ANALYSIS_NOT_READY,
    ),
    ErrorDomain.GAZE_ANALYSIS: (
        ErrorCode.GAZE_ANALYSIS_NOT_FOUND,
        ErrorCode.GAZE_ANALYSIS_NOT_READY,
    ),
    ErrorDomain.EVALUATION: (
        ErrorCode.EVALUATION_NOT_FOUND,
        ErrorCode.EVALUATION_NOT_READY,
    ),
    ErrorDomain.QA: (
        ErrorCode.QA_SESSION_NOT_FOUND,
        ErrorCode.QA_QUESTION_NOT_FOUND,
        ErrorCode.QA_ANSWER_NOT_FOUND,
    ),
    ErrorDomain.REPORT: (
        ErrorCode.REPORT_NOT_FOUND,
        ErrorCode.REPORT_NOT_READY,
    ),
    ErrorDomain.JOB: (
        ErrorCode.JOB_NOT_FOUND,
        ErrorCode.JOB_CANNOT_BE_CANCELLED,
    ),
    ErrorDomain.SYSTEM: (
        ErrorCode.INTERNAL_SERVER_ERROR,
        ErrorCode.DEPENDENCY_UNAVAILABLE,
    ),
}


__all__ = [
    "ERROR_CODES_BY_DOMAIN",
    "ErrorCode",
    "ErrorDomain",
]
